global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: pgcdc
    static_configs:
      - targets:
          - pgcdc:9090
    scrape_interval: 10s
    metrics_path: /metrics
